# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='code',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
