# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_auto_20160111_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
