# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0004_uploadfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
