# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0005_auto_20160220_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user_cre',
            new_name='user_created',
        ),
    ]
