# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ged', '0007_auto_20160220_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='user_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='user_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfile_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='user_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfile_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
