# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0010_auto_20160313_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Folder', verbose_name='Folder'),
        ),
    ]
