# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20160506_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Repository', 'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterModelOptions(
            name='typerepository',
            options={'verbose_name': 'TypeRepository', 'verbose_name_plural': 'TypeRepositories'},
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.TypeRepository', verbose_name='type'),
        ),
    ]
