# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('user_created', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=512)),
                ('contentType', models.CharField(max_length=30)),
                ('version', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_l', models.IntegerField(default=0)),
                ('node_r', models.IntegerField(default=0)),
                ('libelle', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backdrive.Folder')),
                ('user_created', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=256)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('user_created', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfile_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfile_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backdrive.Folder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='user_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
